# Generated by Django 4.2 on 2023-04-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max', models.DecimalField(decimal_places=10, default=0, max_digits=100)),
                ('min', models.DecimalField(decimal_places=10, default=0, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=255)),
                ('tax', models.DecimalField(decimal_places=10, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Oportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchangeBuy', models.CharField(max_length=255)),
                ('profit', models.DecimalField(decimal_places=10, default=0, max_digits=1000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('coin', models.CharField(max_length=255)),
                ('invest', models.DecimalField(decimal_places=10, default=0, max_digits=1000)),
                ('bidPrice', models.DecimalField(decimal_places=10, default=0, max_digits=1000)),
                ('bidQtity', models.DecimalField(decimal_places=10, default=0, max_digits=1000)),
                ('askPrice', models.DecimalField(decimal_places=10, default=0, max_digits=1000)),
                ('askQtity', models.DecimalField(decimal_places=10, default=0, max_digits=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='exchange.account')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin', to='exchange.coin')),
            ],
        ),
        migrations.CreateModel(
            name='AccountMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entries', models.DecimalField(decimal_places=10, default=0, max_digits=1000)),
                ('outs', models.DecimalField(decimal_places=10, default=0, max_digits=1000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_moviment', to='exchange.balance')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='exchange.exchange'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_user', to='bot.user'),
        ),
    ]
